spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:product
    username: sa
    password:
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: "ant-path-matcher"
  web:
    resources:
      add-mappings: false
server:
  port: 5001